[font]
normal = {family = "JetBrainsMono Nerd Font"}
size = 16

[window]
dimensions = {columns = 96 , lines = 60}
decorations = "None"

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"
