[colors.primary]
background = '#2e3440'
foreground = '#5e81ac'

[colors.selection]
text = '#5e81ac'
background = '#88c0d0'

[colors.cursor]
text = '#2e3440'
cursor = '#81a1c1'

[colors.normal]
black   = '#3b4252'
red     = '#cc3335'
green   = '#72d66e'
yellow  = '#dbd07b'
blue    = '#38638e'
magenta = '#6a7d90'
cyan    = '#81a1c1'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f60'
green   = '#88e086'
yellow  = '#e8df97'
blue    = '#acd9ff'
magenta = '#2e5d73'
cyan    = '#35496a'
white   = '#ffffff'
